spring:
  application:
    name: xoxo-service
# -------------------------------- Datasources -------------------------------- #
postgresql:
  datasource:
    jdbc-Url: jdbc:postgresql://ec2-174-129-255-35.compute-1.amazonaws.com:5432/des2jhc9cmkhdg?sslmode=require
    username: tujeqummmczqqx
    password: eb6d00561667904b4c20caa22c690f51dbd289138ee57feb11732452fcdc35a4
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
      poolName: SpringBootHikariPostgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
mysql:
  datasource:
    #jdbc-Url: jdbc:mysql://localhost:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false;useUnicode=true;useJDBCCompliantTimezoneShift=true;useLegacyDatetimeCode=false;serverTimezone=UTC
    jdbc-Url: jdbc:mysql://localhost:3306/dbtest?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=UTF8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
      poolName: SpringBootHikariMysql
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: create
